name: Build .NET Core 9 and Angular

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET Core 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: UserManagementAPI Restore .NET dependencies
        working-directory: BE-NetCore-code/App-api/UserManagementAPI
        run: dotnet restore

      - name: UserManagementAPI Build .NET solution
        working-directory: BE-NetCore-code/App-api/UserManagementAPI
        run: dotnet build --no-restore --configuration Release

      - name: UserManagementAPI Publish .NET project
        working-directory: BE-NetCore-code/App-api/UserManagementAPI
        run: dotnet publish --no-build --configuration Release --output ./publish

      - name: CryptoInvestmentAPI Restore .NET dependencies
        working-directory: BE-NetCore-code/App-api/CryptoInvestmentAPI
        run: dotnet restore

      - name: CryptoInvestmentAPI Build .NET solution
        working-directory: BE-NetCore-code/App-api/CryptoInvestmentAPI
        run: dotnet build --no-restore --configuration Release

      - name: CryptoInvestmentAPI Publish .NET project
        working-directory: BE-NetCore-code/App-api/CryptoInvestmentAPI
        run: dotnet publish --no-build --configuration Release --output ./publish

      - name: Gateway.API Restore .NET dependencies
        working-directory: BE-NetCore-code/App-api/Gateway.API
        run: dotnet restore

      - name: Gateway.API Build .NET solution
        working-directory: BE-NetCore-code/App-api/Gateway.API
        run: dotnet build --no-restore --configuration Release

      - name: Gateway.API Publish .NET project
        working-directory: BE-NetCore-code/App-api/Gateway.API
        run: dotnet publish --no-build --configuration Release --output ./publish

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.0'

      - name: Install Angular dependencies
        working-directory: FE-Angular-code
        run: npm install

      - name: Build Angular application
        working-directory: FE-Angular-code
        run: npm run build
